---@class MechData dataset for adding a new mech to the obj database
---@field Name string the name of the mech, used to find its references
---@field ComponentSize ComponentSize the size of the component when constructing it.
---@field IsResearched boolean set to true if its pre researched, else false.
---@field CanBeConstructed boolean set to true if it can be constructed in the component shop, false otherwise
---@field GiveFreeItem boolean set to true to return a free copy when triggered as an unlock
---@field PriceMetallite number the amount of metallite needed to produce this mech
---@field PriceBjorn number the amount of bjorn needed to produce this mech
---@field PriceMunilon number the amount of munilon needed to produce this mech
---@field PriceSkalaknit number the amount of skalaknit needed to produce this mech
---@field PriceStaff number the amount of staff needed to produce this mech
---@field ProductionDays number the amount of days it takes to produce this mech
---@field HeatResist number the heat resist value of the mech
---@field ImpactResist number the impact resist value of the mech
---@field CurrentResist number the current resist value of the mech
---@field HasMelee boolean Indicates if the mech can use a melee weapon
---@field PassiveArmor number the amount of passive armor the mech has
---@field Weight number the base weight of the mech
---@field Speed number the base speed of the mech
---@field ReloadTime number the base reload time of the mech
---@field BattleTime number the base battle time of the mech (the length of time it has ammo reserves for to shoot)
---@field MechCells MechCell[] the dataset on what cells the mech has
---@field SpriteSmall string the small sprite for the mech
---@field SpriteBig string the big sprite for the mech
---@field SpriteBattle string the sprite sheet for the mech used on the battle screen
---@field SpriteBattleDead string the sprite for a destroyed mech on the battle screen
---@field SpriteMeleeVertical string? the vertical melee attack sprite sheet used on the battle screen. optional if the mech has no melee
---@field SpriteMeleeHorizontal string? the horizontal melee attack sprite sheet used on the battle screen. optional if the mech has no melee

---@class MechCell dataset on what cells a mech has
---@field ModuleType ModuleType module type (1-aux, 2-motor, 3-reactor, 4-gun, 5-cabin)
---@field X number the x coordinate for the cell, use the mod_mech_grid_help.png for help determining the location
---@field Y number the y coordinate for the cell, use the mod_mech_grid_help.png for help determining the location