---@class ds_map A reference handle to the gamemaker ds_map data structure, stores key and value pairs.

---This is an auto generated class definition. 
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_big_holder
---@field text_menu_reload string
---@field text_menu_weight string
---@field discket_ammo_ratio_yellow number
---@field walk_holder table
---@field armor_lr_have_copy table
---@field new_item_type number
---@field text_menu_test string
---@field text_blueprint_empty string
---@field camera_zoom number
---@field discket_melee number
---@field test_surf number
---@field ignite_open boolean
---@field discket_ammo_ratio_red number
---@field text_menu_energy string
---@field cur_sprite_stop number
---@field mech_extra_layer number
---@field save_blueprint_animation number
---@field armor_lr table
---@field monitor_img number
---@field new_item number
---@field reactor_type number
---@field text_menu_send string
---@field st_lua table
---@field scroll number
---@field discket_destruct number
---@field text_menu_ignite string
---@field send_open boolean
---@field text_blueprint_have string
---@field cur_sprite number
---@field text_battle_cost string
---@field cur_item_type number
---@field processor_program_researched boolean
---@field discket_ammo_ratio_white number
---@field test_copy_surf number
---@field cur_sprite_work number
---@field armor_lr_have table
---@field reactor_type_anim number
---@field change boolean
---@field array_lua table
---@field activated boolean
---@field discket_energy_shield number
---@field clean boolean
---@field cur_item number
---@field discket_active_armor number
---@field text_blueprint_type string
---@field change_item_time number
---@field cur_sprite_start number
---@field armor_layers number

---This is an auto generated class definition. 
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_big_holder_mech
---@field defence_melee number
---@field dead boolean
---@field stat_weight number
---@field special_debuf_health number
---@field c_g number
---@field new_item_type number
---@field stat_evasion number
---@field size_paint number
---@field log_damage_laser number
---@field output_for_small_holder number
---@field resist_impact number
---@field bb_armor_damage number
---@field mech_name string
---@field mech_battle_sprite_hor_attack number
---@field have_gun boolean
---@field more_info boolean
---@field name_sh_reload string
---@field buf_armor number
---@field text_lost string
---@field name_lo_temp string
---@field log_overheat number
---@field my_reactor_id number
---@field log_ammo_fire number
---@field my_paint number
---@field defence_energy_shield number
---@field have_torpedoes boolean
---@field mass_wep_type_draw table
---@field turbine_buf number
---@field special_debuf_coolent number
---@field c_b number
---@field stat_repair_drone number
---@field mimic_ammo_ratio_yellow number
---@field stat_energy_output number
---@field stat_dmg_red number
---@field paint_tex nil
---@field text_survived string
---@field log_damage_fire number
---@field resist_heat number
---@field bb_active_armor number
---@field original_speed number
---@field mech_battle_sprite_dead number
---@field deleted boolean
---@field mass_gun_id table
---@field buf_wire_plus number
---@field mirror number
---@field name_sh_hp string
---@field buf_ams number
---@field name_lo_speed string
---@field s_text_typing number
---@field bb_speed_damage number
---@field stat_cabin_safety number
---@field log_ammo_ballistic number
---@field load_ini boolean
---@field my_big_sprite number
---@field start_y number
---@field defence_destruct_sys number
---@field processor_program table
---@field num_of_modules number
---@field special_debuf_attack number
---@field stat_reload_time number
---@field armor_lr table
---@field new_item number
---@field stat_max_weight number
---@field electric_circuits_maximum number
---@field stat_energy_input number
---@field mimic_ammo_ratio_white number
---@field paint_me boolean
---@field mech_speed_buf number
---@field stat_dmg_blue number
---@field log_damage_ballistic number
---@field resist_current number
---@field original_resist_impact number
---@field mech_battle_sprite number
---@field can_have_melee number
---@field text_damaged string
---@field number_of_holders number
---@field aux_laser_heat number
---@field cur_item_type number
---@field buf_wire_minus number
---@field buf_paint number
---@field name_sh_armor string
---@field alpha_control number
---@field name_lo_reload string
---@field log_evasion number
---@field overclock number
---@field bb_reload_damage number
---@field stat_bonus_stability number
---@field my_num number
---@field mech_data_id table
---@field start_x number
---@field defence_active_armor number
---@field stat_speed number
---@field special_debuf_armor number
---@field custom_sprite string
---@field armor_layers number
---@field last_my number
---@field stat_max_temp number
---@field animation_save_sprite boolean
---@field mimic_ammo_ratio_red number
---@field name string
---@field stat_damage number
---@field my_pilot number
---@field original_resist_heat number
---@field number_of_guns number
---@field tired number
---@field name_lo_hp string
---@field bb_injure number
---@field stat_battle_time number
---@field my_metallite_price number
---@field circuits_using number
---@field mech_data number
---@field original_battle_time number
---@field change_name boolean
---@field have_reactor boolean
---@field last_mx number
---@field name_sh_weight string
---@field stat_dps number
---@field log_avg_dist number
---@field original_resist_current number
---@field my_eraser number
---@field sh_paint_sampler number
---@field defence_passive_armor number
---@field dead_pilot boolean
---@field change boolean
---@field c_r number
---@field new_module boolean
---@field cur_item number
---@field name_lo_armor string
---@field mech_number number
---@field bb_energy_shield number
---@field mech_change_id table
---@field shield_buff number
---@field original_armor number
---@field have_needles boolean
---@field name_sh_temp string
---@field stat_dmg_yellow number
---@field oxygen_multiplier number
---@field original_weight number
---@field log_ammo_rocket number
---@field battle_slot number
---@field original_reload_time number
---@field stat_armor number
---@field defence_mod_weight number
---@field heat_sink_module number
---@field have_cabin boolean
---@field number_of_deleted number
---@field special_debuf_speed number
---@field armor_lr_weight number
---@field cur_guns number
---@field item_pos number
---@field log_damage_rocket number
---@field bb_cool_damage number
---@field mech_battle_sprite_ver_attack number
---@field hit_points number
---@field created boolean
---@field name_sh_speed string
---@field name_lo_weight string
---@field stat_dmg_white number
---@field log_ammo_laser number
---@field my_paint_buf number
---@field hover boolean

---This is an auto generated class definition. 
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_big_holder_reactor
---@field press number
---@field have_bonus boolean
---@field mod_output number
---@field stat_energy number
---@field name string
---@field original_max_heat number
---@field plasma_coord_y number
---@field stat_weight number
---@field reactor_spr_big_stop number
---@field my_holder number
---@field i number
---@field name_stability string
---@field text_engine_off string
---@field load_ini boolean
---@field blink_ignite number
---@field start_y number
---@field original_coolent_power number
---@field buf_coolent_power number
---@field buf_sys_mult number
---@field plasma_coord_mult number
---@field reactor_spr_big number
---@field stat_coolent_power number
---@field original_weight number
---@field number_of_kernel number
---@field reactor_type number
---@field overcharge_output number
---@field buf_max_temp number
---@field name_output string
---@field mech_data number
---@field buf_work_heat number
---@field number_of_deleted number
---@field plasma_coord_z number
---@field surf_eng_off number
---@field max_press number
---@field reactor_spr_big_work number
---@field stat_work_heat number
---@field reaction number
---@field slowdown number
---@field additional_wires number
---@field buf_sys_external number
---@field reactor_reload_mod number
---@field name_weight string
---@field text_engine_running string
---@field buf_mod_output number
---@field name_limit string
---@field number_of_holders number
---@field item_pos number
---@field stat_max_heat number
---@field have_base boolean
---@field view_sprite number
---@field my_mech number
---@field stat_output number
---@field plasma_coord_x number
---@field reactor_spr_big_start number
---@field stat_system_buf number
---@field original_work_heat number
---@field reactor_number number
---@field my_num number
---@field mech_data_id table
---@field original_output number
---@field plasma_distance number
---@field created boolean
---@field start_x number
---@field reaction_multiplier number
---@field mod_max_temp number
---@field ignite number
---@field new_module boolean
---@field slowdown_multiplier number
---@field deleted boolean
---@field buf_sys_inner number
---@field reactor_spr number
---@field hover boolean

---This is an auto generated class definition. 
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_big_holder_weapon
---@field original_energy number
---@field set_point_weight number
---@field special_acc_buf number
---@field wep_prior table
---@field stat_energy number
---@field weapon_number number
---@field name string
---@field stat_penetration number
---@field buf_wire_plus number
---@field sound_pack number
---@field stat_weight number
---@field set_point_current number
---@field stat_damage number
---@field energy_buffed number
---@field rate_of_fire number
---@field weapon_type_num number
---@field my_holder number
---@field special_rtf_buf number
---@field change_x number
---@field special_buf_type number
---@field weapon_spr_big number
---@field original_penetration number
---@field start_y number
---@field special_ele_buf number
---@field set_point_max number
---@field special_weight_buf number
---@field original_accuracy number
---@field original_weight number
---@field special_num_buf number
---@field number_of_deleted number
---@field homing_power number
---@field size_huge number
---@field set_point_energy number
---@field check_special boolean
---@field special_sp_buf number
---@field change_y number
---@field original_rate_of_fire number
---@field number_of_holders number
---@field original_damage number
---@field item_pos number
---@field set_point_penetration number
---@field special_life_buf number
---@field my_mech number
---@field stat_dps number
---@field buf_wire_minus number
---@field set_point_accuracy number
---@field weapon_type string
---@field special_pen_buf number
---@field pretend_gun number
---@field special_buf_slow number
---@field my_num number
---@field weapon_spr number
---@field created boolean
---@field start_x number
---@field special_dmg_buf number
---@field set_point_fire_speed number
---@field original_speed number
---@field new_module boolean
---@field weapon_data number
---@field deleted boolean
---@field accuracy_fault number
---@field hover boolean
---@field blue_length number the range of a blue weapon

---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_content_magnet
---@field size_x number
---@field position_y number
---@field sort_anim number
---@field sort_now boolean
---@field list_magnet table
---@field array_lua table
---@field check_list boolean
---@field activated boolean
---@field position_x number
---@field size_y number
---@field sort_items number
---@field surf_magnet_normal number
---@field my_window number
---@field move_y number
---@field st_lua table
---@field scroll number
---@field number_of_deleted number
---@field item_height number
---@field number_of_items number

---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_content_weapons
---@field size_x number
---@field position_y number
---@field sort_anim number
---@field sort_now boolean
---@field array_lua table
---@field check_list boolean
---@field activated boolean
---@field position_x number
---@field size_y number
---@field sort_items number
---@field my_window number
---@field move_y number
---@field list_weapon table
---@field surf_weapon_normal number
---@field st_lua table
---@field scroll number
---@field number_of_deleted number
---@field item_height number
---@field number_of_items number

---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_content_solenoid
---@field size_x number
---@field position_y number
---@field sort_anim number
---@field list_solenoid table
---@field surf_solenoid_normal number
---@field sort_now boolean
---@field array_lua table
---@field check_list boolean
---@field activated boolean
---@field position_x number
---@field size_y number
---@field sort_items number
---@field my_window number
---@field move_y number
---@field st_lua table
---@field scroll number
---@field number_of_deleted number
---@field item_height number
---@field number_of_items number

---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_content_reactor
---@field size_x number
---@field position_y number
---@field sort_anim number
---@field sort_now boolean
---@field array_lua table
---@field check_list boolean
---@field activated boolean
---@field surf_reactor_normal number
---@field list_reactor table
---@field position_x number
---@field size_y number
---@field sort_items number
---@field my_window number
---@field move_y number
---@field st_lua table
---@field scroll number
---@field number_of_deleted number
---@field item_height number
---@field number_of_items number

--------------------------------------------
--Documentation for used mod functions -----
--------------------------------------------
--Added this file to give the IDE info on what the mod functions return and use for params
--Game is made in GameMaker
--See the gamemaker documentation for the implimentation of the global functions
--example: variable_global_set, ds_map_add, sprite_add
--the exposed functions can be found in the list_of_functions.txt file

---@type table<string, string>
mod_info = mod_info
---This function is used to create a new, empty DS map and will return a Handle to it which is then used to access the data structure in all other DS map functions.
---@type fun(): ds_map
ds_map_create = ds_map_create
---This function should be used to add sets of key/value pairs into the specified DS map.
---@type fun(map: ds_map, key: string, value: any)
ds_map_add = ds_map_add
---With this function you can retrieve all of the keys that a DS map contains.
---@type fun(id: ds_map) : table
ds_map_keys_to_array = ds_map_keys_to_array
---With this function you can get the value from a specified key.
---@type fun(id: ds_map, key: string) : any|nil
ds_map_find_value = ds_map_find_value
---This function returns an array with the variable names from a struct.
---@type fun(id: number) : table
struct_get_names = struct_get_names
---With this function you can set the value of a given global variable.
---@type fun(key: string, value: any)
variable_global_set = variable_global_set
---With this function you can get the value from a given named global variable
---@type fun(key: string): value: any
variable_global_get = variable_global_get
---This function will add an image as a sprite
---@type fun(filepath: string, number_of_images: number, removeback: boolean, smooth: boolean, xorig: number, yorig: number): value: number
sprite_add = sprite_add
---This function will merge the sprite indexed in argument 1 ("ind2") with that which is indexed in argument 0 ("ind1").
---@type fun(ind1: number, ind2: number)
sprite_merge = sprite_merge
---This function will return the index of a newly created sprite that is a duplicate (copy) of the one input as the "index" argument.
---@type fun(index: number) :number|-1
sprite_duplicate = sprite_duplicate
---This function will delete a sprite from the game, freeing any memory that was reserved for it.
---@type fun(index: number)
sprite_delete = sprite_delete
---This function gets the unique identifying index for a game asset from its name.
---@type fun(name: string): any
asset_get_index = asset_get_index
---This function creates a pop-up message box which displays the given string and a button marked "Ok" to close it.
---@type fun(message: string|number)
show_message = show_message
---With this function you can create a new instance of the specified object at any given point within the room and at the depth specified.
---@type fun(x: number, y: number, depth: number, obj: any): any
instance_create_depth = instance_create_depth
---With this function you can check if a key is pressed, as imput it uses virtual key codes
---@type fun(virtualKey: number)
keyboard_check_pressed = keyboard_check_pressed
---This function is used to create a surface and will return the index of the surface which should be stored in a variable for future function calls.
---@type fun(width: number, height: number)
surface_create = surface_create
---With this function you set all further drawing to the target surface rather than the screen and in this way you can tell GameMaker to only draw specific things to the specified surface.
---@type fun(surface_id: number)
surface_set_target = surface_set_target
---This function can be used to clear the entire screen with a given colour and the alpha component of the destination is set to the value you have set.
---@type fun(col_id: number, alpha: number)
draw_clear_alpha = draw_clear_alpha
---This function draws the given sprite and sub-image at a position.
---@type fun(sprite: number, subimg: number, x: number, y: number)
draw_sprite = draw_sprite
---This function resets all further drawing from the target surface back to the screen.
---@type fun()
surface_reset_target = surface_reset_target
---This function will save a surface to disc using the given filename. The surface must be saved as a *.png format file.
---@type fun(surface_id: number, fname: string)
surface_save = surface_save
---When you are working with surfaces, you should always use this function whenever you are finished using them.
---@type fun(surface_id: number)
surface_free = surface_free
---When you are working with surfaces, you should always use this function whenever you are finished using them.
---@type fun(ind:number, fname:string, imgnumb:number, removeback:boolean, smooth:boolean, xorig:number, yorig:number)
sprite_replace = sprite_replace