---@class ds_map A reference handle to the gamemaker ds_map data structure, stores key and value pairs.

---This is an auto generated class definition. 
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_database
---@field tutorial_weapon_showed number
---@field text_controls_zoomin string
---@field endgame_text_ammo_yellow string
---@field text_context_construction_weapon_rateoffire string
---@field text_context_construction_mech_speed string
---@field content_motors number
---@field text_context_construction_mech_adspeed string
---@field ingame_month number
---@field eng_program_text_description string
---@field text_context_battle_camera string
---@field eng_defence_pa_hint_bottom string
---@field mass_safetys table
---@field tutorial_paint_showed number
---@field text_days string
---@field endgame_text_walked string
---@field programs_load table
---@field text_controls_camright string
---@field endgame_stat_soldier number
---@field text_context_construction_weapon_modprice string
---@field buf_res_metallite number
---@field text_tutorial_put_reactor string
---@field text_context_construction_mech_menu_repair string
---@field t_mech_holder table
---@field text_team_eng string
---@field text_context_city_energy string
---@field mech_research number
---@field in_resource_waste number
---@field eng_menu_piston string
---@field rep_durability string
---@field eng_defence_ammo string
---@field mass_mechs_hangar_for_pilots table
---@field tutorial_defend_city number
---@field endgame_text_res_munilon string
---@field mon_jul string
---@field text_context_production_numbers string
---@field endgame_stat_grappler number
---@field position_voices_y number
---@field text_context_construction_reactor_work_heat string
---@field piston_stat table
---@field text_tutorial_hangar_1 string
---@field text_context_construction_mech_hitpoints string
---@field text_context_battle_retreat string
---@field eng_menu_cabins string
---@field music_slowdown number
---@field day_name string
---@field month_name string
---@field tutorial_atom_showed number
---@field scroll_music number
---@field endgame_text_crab string
---@field mon_aug string
---@field endgame_stat_bases number
---@field text_context_construction_weapon_test_single string
---@field text_context_construction_reactor_cooling_power string
---@field content_weapons number
---@field text_tutorial_beacon string
---@field text_context_construction_mech_energy string
---@field text_context_battle_move string
---@field city_parts_stat number
---@field eng_defence_text_coating string
---@field mass_weapons table
---@field tutorial_repair_showed number
---@field text_controls_pause string
---@field endgame_text_ammo_red string
---@field text_context_construction_weapon_points_rateoffire string
---@field text_context_construction_mech_resistances string
---@field content_magnets number
---@field text_context_city_overall string
---@field eng_menu_vvt string
---@field text_context_battle_ammo string
---@field eng_defence_energy string
---@field start_ambient boolean
---@field mass_pistons table
---@field tutorial_hantwo_showed number
---@field endgame_text_swarm string
---@field program_text_desc table
---@field mon_oct string
---@field text_controls_camera string
---@field endgame_stat_res_skalaknit number
---@field armor_rl_middle_stat table
---@field text_context_construction_weapon_distance_type string
---@field text_tutorial_pilots string
---@field text_context_construction_mech_menu_paint string
---@field s_radio_noise number
---@field text_context_city_district_resources string
---@field in_mouse number
---@field text_hangar string
---@field eng_menu_motors string
---@field rep_armor string
---@field day_tue string
---@field mass_magnets table
---@field endgame_text_res_bjorn string
---@field mon_feb string
---@field text_context_construction_weapon_test_wirespower string
---@field endgame_stat_flower number
---@field position_music_y number
---@field text_context_construction_reactor_test_levers string
---@field t_reactor_holder table
---@field minus_metallite number
---@field text_tutorial_district string
---@field text_context_construction_mech_heat_from_reload string
---@field text_context_battle_pilot_aux string
---@field text_save_menu string
---@field eng_defence_weight string
---@field day_fri string
---@field scroll_misc number
---@field endgame_text_bull string
---@field daily_news_length number
---@field text_context_construction_weapon_test_aux string
---@field endgame_stat_ammo_white number
---@field text_context_construction_mech_unused_weight string
---@field t_pilot_mass table
---@field content_safetys number
---@field weapon_stat ds_map[] the stat values for weapons as ds_map objects
---@field text_context_construction_mech_battle_cost string
---@field text_intro string
---@field text_context_battle_map string
---@field text_exit_battle string
---@field eng_defence_shield string
---@field tutorial_put_mech_showed number
---@field prev_m_y number
---@field text_controls_fullscreen string
---@field endgame_stat_taran number
---@field text_metallite string
---@field text_context_construction_weapon_points_damage string
---@field text_tutorial_weapon string
---@field text_context_construction_mech_passive_armor string
---@field content_injectors number
---@field text_context_city_humans string
---@field eng_menu_solenoid string
---@field text_components string
---@field eng_defence_coating string
---@field text_bjorn string
---@field mass_motors table
---@field tutorial_eng_showed number
---@field endgame_text_soldier string
---@field mon_may string
---@field text_controls_artillery string
---@field endgame_stat_res_metallite number
---@field next_battle_music boolean
---@field text_context_construction_weapon_blueprint string
---@field minus_skalaknit number
---@field text_tutorial_menu string
---@field text_context_construction_mech_maxtemp string
---@field text_context_city_damage string
---@field eng_menu_magnet string
---@field surf_daily_news number
---@field day_sun string
---@field tutorial_calendar_showed number
---@field endgame_text_grappler string
---@field text_context_construction_weapon_test_water string
---@field endgame_stat_caterpillar number
---@field position_misc_y number
---@field last_music number
---@field text_context_construction_reactor_resistances string
---@field minus_bjorn number
---@field text_tutorial_components string
---@field text_context_construction_mech_evasion string
---@field text_context_battle_pause string
---@field eng_defence_text_explode string
---@field text_controls_zoomout string
---@field endgame_text_bases string
---@field text_context_construction_weapon_test_armordown string
---@field text_context_construction_mech_stability_regen string
---@field content_pistons number
---@field text_context_construction_mech_ammo string
---@field mech_stat ds_map[] the stat values for mechs as ds_map objects
---@field show_sort number
---@field ingame_year number
---@field eng_program_text_overclocking string
---@field text_context_battle_freewill string
---@field text_research string
---@field eng_defence_pa_hint_top string
---@field mass_solenoids table
---@field tutorial_pilots_blinked number
---@field text_controls_camup string
---@field endgame_stat_stingray number
---@field array_lua table
---@field text_context_construction_weapon_points string
---@field buf_res_munilon number
---@field text_tutorial_repair string
---@field text_context_construction_mech_menu_shield string
---@field text_team_sci string
---@field text_context_city_food string
---@field eng_menu_reactors string
---@field rep_reload_time string
---@field eng_defence_armor string
---@field motor_stat table
---@field tutorial_district_showed number
---@field endgame_text_res_skalaknit string
---@field mon_jun string
---@field endgame_stat_mechs number
---@field news boolean
---@field text_context_construction_table string
---@field text_tutorial_hangar_2 string
---@field text_context_construction_mech_impact_resist string
---@field text_context_battle_zoom string
---@field eng_menu_injector string
---@field day_number number
---@field mass_injectors table
---@field tutorial_battle_showed number
---@field scroll_voices number
---@field endgame_text_flower string
---@field to_menu_message boolean
---@field text_context_construction_weapon_test_switcher string
---@field endgame_stat_battletime number
---@field text_context_construction_reactor_ignite string
---@field text_tutorial_beginning string
---@field text_context_construction_mech_energyshield string
---@field text_context_battle_page string
---@field eng_defence_text_distribution string
---@field reactor_stat table
---@field tutorial_research_showed number
---@field text_controls_target string
---@field endgame_text_ammo_white string
---@field atom_bomb_stat number
---@field text_context_construction_weapon_points_weight string
---@field text_context_construction_mech_send string
---@field content_mechs number
---@field safety_stat table
---@field text_context_city_wounded string
---@field eng_menu_weapons string
---@field text_context_battle_artillery string
---@field text_engineering string
---@field eng_defence_melee string
---@field mass_reactors table
---@field tutorial_map_showed number
---@field program_text_name table
---@field endgame_text_taran string
---@field mon_sep string
---@field text_controls_camleft string
---@field endgame_stat_snake number
---@field text_context_construction_weapon_distance_view string
---@field buf_res_bjorn number
---@field anim_exit number
---@field text_tutorial_put_mech string
---@field text_context_construction_mech_menu_processor string
---@field text_context_city_district_stats string
---@field in_music number
---@field eng_menu_nucaux string
---@field rep_coolent string
---@field eng_defence_active_armor string
---@field day_wed string
---@field mass_mechs table
---@field tutorial_defence_showed number
---@field endgame_text_res_metallite string
---@field mon_jan string
---@field cabin_stat table
---@field text_context_production_days string
---@field endgame_stat_giants number
---@field position_voices_x number
---@field text_context_construction_reactor_work_coolent string
---@field minus_munilon number
---@field sort_text table
---@field text_tutorial_electro string
---@field text_context_construction_mech_heat_from_shoot string
---@field text_context_battle_resources string
---@field eng_menu_auxility string
---@field day_mon string
---@field endgame_text_caterpillar string
---@field daily_news_text string
---@field mon_apr string
---@field text_context_construction_weapon_test_distance string
---@field endgame_stat_ammo_yellow number
---@field text_context_construction_mech_weight string
---@field pilot_stat table
---@field content_solenoids number
---@field text_tutorial_battle string
---@field text_context_construction_mech_blueprint string
---@field was_ambient boolean
---@field text_context_battle_mech string
---@field eng_defence_text_blocks_damage string
---@field tutorial_put_reactor_showed number
---@field mass_controls table
---@field text_controls_palette string
---@field endgame_stat_walked number
---@field text_context_construction_weapon_points_energy string
---@field magnet_stat table
---@field text_context_construction_mech_rename string
---@field content_kernels number
---@field text_context_city_life string
---@field eng_menu_theaux string
---@field eng_defence_destruct string
---@field tutorial_hangar_showed number
---@field endgame_text_stingray string
---@field mon_nov string
---@field state_music number
---@field text_controls_camdown string
---@field endgame_stat_res_munilon number
---@field armor_rl_end_stat table
---@field text_context_construction_weapon_distance string
---@field text_tutorial_paint string
---@field text_context_construction_mech_menu_elec string
---@field text_context_city_district_levels string
---@field text_skalaknit string
---@field eng_menu_mechs string
---@field day_thu string
---@field motor_research number
---@field mass_loaded_pilot_mech_id table
---@field tutorial_components_showed number
---@field grid_image_save_seed number
---@field endgame_text_mechs string
---@field mon_dec string
---@field text_context_construction_weapon_test_wires string
---@field endgame_stat_crab number
---@field position_music_x number
---@field text_context_construction_reactor_temperature string
---@field sort_num number
---@field m_exit boolean
---@field text_tutorial_defence string
---@field text_context_construction_mech_external_res string
---@field text_context_battle_pilot string
---@field eng_defence_text_melee string
---@field endgame_text_battletime string
---@field daily_news_counter number
---@field mod_text_position number
---@field text_context_construction_weapon_test_armorup string
---@field endgame_stat_ammo_red number
---@field text_context_construction_mech_test_chamber string
---@field content_reactors number
---@field solenoid_stat ds_map[] the stat values for solenoids as ds_map objects
---@field text_tutorial_atom string
---@field text_context_construction_mech_basic_heat string
---@field text_context_battle_fullscreen string
---@field eng_defence_passive_armor string
---@field tutorial_pilots_showed number
---@field hangar_mechs number
---@field mass_cabins table
---@field prev_m_x number
---@field text_controls_command string
---@field endgame_stat_swarm number
---@field text_context_construction_weapon_points_accuracy string
---@field buf_res_skalaknit number
---@field text_tutorial_research string
---@field text_context_construction_mech_menu_weight string
---@field content_cabins number
---@field text_context_city_goods string
---@field beacon_lure_stat number
---@field eng_menu_safety string
---@field rep_speed string
---@field eng_defence_battle_time string
---@field st_lua table
---@field tutorial_electro_showed number
---@field endgame_text_snake string
---@field mon_mar string
---@field text_munilon string
---@field endgame_stat_res_bjorn number
---@field text_context_construction_weapon_accuracy string
---@field text_tutorial_map string
---@field text_context_construction_mech_max_cooling string
---@field text_context_city_components string
---@field eng_menu_kernel string
---@field day_sat string
---@field mass_kernels table
---@field tutorial_beacon_showed number
---@field endgame_text_giants string
---@field cabin_research number
---@field text_context_construction_weapon_test_turnon string
---@field endgame_stat_bull number
---@field position_misc_x number
---@field text_context_construction_reactor_max_temperature string
---@field text_tutorial_calendar string
---@field kernel_stat table
---@field text_context_construction_mech_engineer_cost string
---@field injector_stat table
---@field text_context_battle_pallete string
---@field eng_defence_text_energy string

---This is an auto generated class definition. 
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_research
---@field condition number 0|1|2|3 condition (0-closed, 1-opened, 2-researching, 3-researched)
---@field progression number
---@field res_type number
---@field opened number
---@field ln_res table
---@field give_item boolean when true indicates the research will give a free item upon completion
---@field researching_anim number
---@field text string
---@field res_number number the number for the research as found in the debug (F6) of the research screen (upper left white number)
---@field n_ln_res number
---@field require_staff number the number of required staff to research
---@field check_research number
---@field link table
---@field meet boolean
---@field array_lua table
---@field new_research boolean
---@field just_researched boolean
---@field blink number
---@field require_days_max number the initial required days to complete the research
---@field next_day number
---@field st_lua table
---@field res_under_type number
---@field require_days number the remaining days to complete the research
---@field text_days string
---@field text_staff string

---This is an auto generated class definition. 
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_component_shop
---@field piston_start_x number
---@field text_max_pressure string
---@field text_beacon string
---@field text_reaction string
---@field safety_start_x number
---@field comp_reactor table
---@field text_current_res string
---@field comp_beacon game_obj_component
---@field show_menu boolean
---@field text_multiplier string
---@field text_impact_res string
---@field new_item_type number
---@field minus_place number
---@field wheel_size_img number
---@field comp_safety table
---@field text_damage string
---@field text_armor string
---@field add boolean
---@field price_metallite number
---@field text_coolent string
---@field mech_start_y number
---@field text_menu_weapon_size string
---@field text_weight string
---@field light_up_table boolean
---@field text_reload string
---@field comp_wep table
---@field text_days string
---@field text_power_motor string
---@field price_skalaknit number
---@field comp_kernel table
---@field text_speed_motor string
---@field next_day boolean
---@field text_skalaknit string
---@field kernel_start_y number
---@field text_aux string
---@field comp_magnet table
---@field disassemble_pressed number
---@field cabin_start_x number
---@field injector_start_y number
---@field text_slowdown string
---@field text_heat string
---@field text_metallite string
---@field text_rocket string
---@field text_firespeed string
---@field text_menu_reactors string
---@field t_reaction_slowdown number
---@field days_left number
---@field motor_start_y number
---@field comp_piston table
---@field text_output string
---@field text_move_z string
---@field text_safety string
---@field new_item_data_type number
---@field text_menu_support string
---@field text_energy string
---@field text_bjorn string
---@field change boolean
---@field comp_rocket number
---@field activated boolean
---@field text_penetration string
---@field comp_city_parts number
---@field mech_start_x number
---@field cur_item number
---@field text_menu_to_order string
---@field text_weapons string
---@field order_pressed number
---@field text_menu_add string
---@field text_district string
---@field weapon_start_y number
---@field text_armor_parts string
---@field price_munilon number
---@field comp_injector table
---@field text_accuracy string
---@field text_speed_mech string
---@field text_menu_hangar_b string
---@field kernel_start_x number
---@field text_pressure string
---@field price_staff number
---@field comp_lr_armor_middle table
---@field injector_start_x number
---@field text_city_parts string
---@field play_sound boolean
---@field reactor_start_y number
---@field text_menu_order string
---@field text_battle string
---@field motor_start_x number
---@field hanger_mass table[]
---@field comp_motor table
---@field text_temp string
---@field text_move_y string
---@field piston_start_y number
---@field st_lua table
---@field weapon_size number
---@field safety_start_y number
---@field comp_cabin table
---@field show_menu_img number
---@field text_munilon string
---@field text_control string
---@field text_induction string
---@field text_menu_to_disassemble string
---@field weapon_start_x number
---@field comp_solenoid table
---@field t_armor_parts number
---@field comp_engineer number
---@field cur_item_type number
---@field text_menu_weapons string
---@field text_menu_hangar_a string
---@field text_power_solenoid string
---@field t_city_parts number
---@field comp_lr_armor_end table
---@field array_lua table
---@field reactor_start_x number
---@field text_menu_mechs string
---@field hangar_order number
---@field comp_mech table
---@field cabin_start_y number
---@field price_bjorn number
---@field text_staff string
---@field text_move_x string
---@field research_weapon_size boolean
---@field text_heat_res string

---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_component
---@field item_pos number
---@field size_x number
---@field size_y number
---@field size ComponentSize the size of the component when constructing it.
---@field logo number the index of the sprite, use -4 to auto set it
---@field logo_index number
---@field researched boolean when true the component can be constructed
---@field comp_type ComponentType the type of component
---@field comp_data_type number the index number of the component

---This is an auto generated class definition. 
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_battle_map
---@field enemy_next number
---@field light_num number
---@field camera_center_y number
---@field monster_count number
---@field number_of_alife_mechs number
---@field map_mask number
---@field time_to_spawn boolean
---@field manual_order_time number
---@field sound_tank_high_freq number
---@field point_B_y number
---@field fullscreen_battle boolean
---@field mission_time_rising number
---@field main_data_sound table
---@field sound_laser_med_freq number
---@field buf_mnstr_sp number
---@field sound_corrosion_low_freq number
---@field boss_maze table
---@field fast_room boolean
---@field palettes_tex nil
---@field wave_reload_time_climax number
---@field battle_full_time number
---@field surf_circle_effects number
---@field text_entering string
---@field text_artillery string
---@field text_actions string
---@field mon_con_base number
---@field giant_new_phase boolean
---@field text_no_artillery string
---@field map_storm boolean
---@field sound_plasma_high_freq number
---@field main_sounds_amount number
---@field sound_fastrocket_low_freq number
---@field maay number
---@field continue_left number
---@field first_battle number
---@field minimap_row number
---@field lut_number number
---@field save_gif boolean
---@field was_defending_city boolean
---@field collect_sound number
---@field swarm_next number
---@field even table
---@field text_legend_bosses string
---@field load_leg_damage table
---@field camera_center_x number
---@field next_second boolean
---@field map_logic_task number
---@field leader_id number
---@field point_B_x number
---@field text_wrong_position string
---@field mission_time_resolution number
---@field sound_laser_low_freq number
---@field buf_metallite_reward number
---@field text_mech_not_selected string
---@field sound_corrosion_high_freq number
---@field l_y number
---@field boss_id number
---@field wave_max_rising number
---@field show_no_artillery_message number
---@field surf_slowdown_tex number
---@field text_scanning string
---@field red_maze table
---@field battle_copy_surf number
---@field underwater_part_type number
---@field surf_circle_artillery number
---@field have_enemy_base boolean
---@field storm_part_type number
---@field gold_maze table
---@field map_type number
---@field giant_id number
---@field text_new_position string
---@field map_cell_danger number
---@field last_maze_manual_order number
---@field sound_fastrocket_high_freq number
---@field pilot_talk_order number
---@field maax number
---@field wave_time_rising number
---@field text_targets string
---@field text_slow string
---@field surf_global_lum number
---@field text_retreat_progress string
---@field text_failed string
---@field reactivate_spawns boolean
---@field srf_minimap number
---@field camera number
---@field gif_image number
---@field text_order_special string
---@field sound_railgun_med_freq number
---@field point_A_y number
---@field mission_time_climax number
---@field sound_laser_high_freq number
---@field text_mech_dead string
---@field wheel_action number
---@field l_x number
---@field boss_dead boolean
---@field bjorn_reward number
---@field wave_max_resolution number
---@field text_legend_walls string
---@field battle_surf number
---@field surf_map_art number
---@field underwater_part number
---@field munillon_reward number
---@field light_sys_mass table
---@field storm_part number
---@field gold_buf table
---@field giant_damage_y number
---@field map_biohazard boolean
---@field sound_minigun_med_freq number
---@field wipe_enemy_base boolean
---@field mini_progress number
---@field skalaknit_reward number
---@field wave_time_resolution number
---@field show_wrong_pos_message number
---@field text_speedup string
---@field battle_pause boolean
---@field load_damaged_giant boolean
---@field surf_gen_map number
---@field start_close_anim boolean
---@field old_mech_phy_id table
---@field text_available string
---@field cam_y number
---@field grid_low number
---@field text_progress string
---@field giant_type number
---@field text_order_retreat string
---@field point_A_x number
---@field sound_railgun_low_freq number
---@field manual_order number
---@field new_grid number
---@field buf_skalaknit_reward number
---@field mission_stage string
---@field sound_flame_med_freq number
---@field buf_eng_reward number
---@field first_pause number
---@field an_time number
---@field boss_count number
---@field wave_max_climax number
---@field mech_slot_target table
---@field text_legend_squad string
---@field battle_speed_timer number
---@field mech_id table
---@field text_focus_fire string
---@field one_of_mech_swallowed boolean
---@field start boolean
---@field storm_move_timer number
---@field camera_zoom number
---@field giant_damage_x number
---@field map_resource number
---@field spawner_mass table
---@field sound_tesla_many number
---@field map_amount_turrets number
---@field sound_minigun_low_freq number
---@field buf_munillon_reward number
---@field winning_present_count number
---@field text_tutorial_B string
---@field blue_maze table
---@field wave_time_climax number
---@field add_stage_progress boolean
---@field retreat_mission boolean
---@field mech_phy_id table
---@field enter_enemy_base boolean
---@field cam_x number
---@field giant_ph_scream boolean
---@field text_order_fire string
---@field manual_camera boolean
---@field sound_railgun_high_freq number
---@field buf_sci_reward number
---@field mission_progress number
---@field sound_flame_low_freq number
---@field action_move_time number
---@field mech_selecting_y number
---@field text_legend_resources string
---@field show_labyrinth_legend boolean
---@field stage_progress number
---@field enemy_sys_mass table
---@field monster_pull_type number
---@field light_next number
---@field map_number number
---@field sound_tank_med_freq number
---@field map_amount_spawners number
---@field thing_created boolean
---@field mnstr_sp number
---@field sound_minigun_high_freq number
---@field buf_monster_count number
---@field boss_time_to_move number
---@field add_resource number
---@field wave_reload_time_rising number
---@field text_inside string
---@field battle_mechs_page number
---@field text_giant_near string
---@field move_line_num number
---@field progressing boolean
---@field scan_for_enemy_base number
---@field mon_con_empty number
---@field giant_ph_rest boolean
---@field text_order_basic string
---@field artillery_shells number
---@field make_it_dark number
---@field sound_plasma_med_freq number
---@field sound_flame_high_freq number
---@field count_gif number
---@field metallite_reward number
---@field weapon_data_sound table
---@field text_temp string
---@field action_last_sound number
---@field rob table
---@field swarm_sys_mass table
---@field mech_selecting_x number
---@field text_legend_exits string
---@field show_giant_is_near number
---@field v_grid number
---@field text_complete string
---@field sh_color_LUT_sampler number
---@field base_plant number
---@field enemy_num number
---@field st_lua table
---@field camera_radius number
---@field monster_max number
---@field scroll number
---@field map_music_task number
---@field map_amount_brucus number
---@field sound_tank_low_freq number
---@field sound_minigun_far number
---@field sound_corrosion_med_freq number
---@field sand_storm boolean
---@field text_tutorial_A string
---@field wave_reload_time_resolution number
---@field surf_mega_light number
---@field battle_gif_surf number
---@field text_entering_long string
---@field ending_task boolean
---@field mon_con_defence number
---@field giant_ph_chase boolean
---@field text_no_base string
---@field map_task number
---@field array_lua table
---@field sound_plasma_low_freq number
---@field tab_time number
---@field sound_fastrocket_med_freq number
---@field buf_bjorn_reward number
---@field minimap_show_big boolean
---@field swarm_num number
---@field mech_selecting boolean
---@field text_legend_enemies string
---@field show_found_base_message number

---This is an auto generated class definition. 
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_weapon_test
---@field text_accuracy string
---@field move_x number
---@field overall_damage_mass table
---@field hit_nmbr number
---@field text_shots string
---@field current_type number
---@field show_energy_sim number
---@field test_reload_time_red number
---@field overall_damage number
---@field damage_nmbr number
---@field hit_mass table
---@field weapon_description table
---@field start number
---@field text_dest_armor string
---@field single_mod number
---@field load_ini boolean
---@field test_copy_surf number
---@field text_damage string
---@field armor_buf number
---@field miss_nmbr number
---@field target number
---@field test_surf number
---@field damage_mass table
---@field water_mod number
---@field simulate_energy number
---@field gun_id number
---@field activated boolean
---@field miss_mass table
---@field text_hits string
---@field test_reload_time_yellow number
---@field monitor_img number
---@field simulate_aux number
---@field scroll number
---@field test_reload_time_white number
---@field text_misses string
---@field text_pot_damage string

---This is an auto generated class definition. 
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_research_panel
---@field double_click boolean
---@field tree_slot_height number
---@field min_size_x number
---@field research_surf number
---@field last_y number
---@field size_ratio number
---@field number_of_res number
---@field old_ms_y number
---@field mres table[] contains the research items that will be put on the research tree, does not contain the reference to the current research state see game_research_item for that
---@field tree_number number
---@field last_x number
---@field old_ms_x number
---@field tree_width number
---@field last_m_x number
---@field research_desc_move number
---@field base_size_h number
---@field array_lua table
---@field max_size_x number
---@field activated boolean
---@field size_y number
---@field tree_slot_width number
---@field st_lua table
---@field sp_zoom number
---@field size_x number

---This is an auto generated class definition. 
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_big_holder
---@field text_menu_reload string
---@field text_menu_weight string
---@field discket_ammo_ratio_yellow number
---@field walk_holder table
---@field armor_lr_have_copy table
---@field new_item_type number
---@field text_menu_test string
---@field text_blueprint_empty string
---@field camera_zoom number
---@field discket_melee number
---@field test_surf number
---@field ignite_open boolean
---@field discket_ammo_ratio_red number
---@field text_menu_energy string
---@field cur_sprite_stop number
---@field mech_extra_layer number
---@field save_blueprint_animation number
---@field armor_lr table
---@field monitor_img number
---@field new_item number
---@field reactor_type number
---@field text_menu_send string
---@field st_lua table
---@field scroll number
---@field discket_destruct number
---@field text_menu_ignite string
---@field send_open boolean
---@field text_blueprint_have string
---@field cur_sprite number
---@field text_battle_cost string
---@field cur_item_type number
---@field processor_program_researched boolean
---@field discket_ammo_ratio_white number
---@field test_copy_surf number
---@field cur_sprite_work number
---@field armor_lr_have table
---@field reactor_type_anim number
---@field change boolean
---@field array_lua table
---@field activated boolean
---@field discket_energy_shield number
---@field clean boolean
---@field cur_item number
---@field discket_active_armor number
---@field text_blueprint_type string
---@field change_item_time number
---@field cur_sprite_start number
---@field armor_layers number

---This is an auto generated class definition. 
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_big_holder_mech
---@field defence_melee number
---@field dead boolean
---@field stat_weight number
---@field special_debuf_health number
---@field c_g number
---@field new_item_type number
---@field stat_evasion number
---@field size_paint number
---@field log_damage_laser number
---@field output_for_small_holder number
---@field resist_impact number
---@field bb_armor_damage number
---@field mech_name string
---@field mech_battle_sprite_hor_attack number
---@field have_gun boolean
---@field more_info boolean
---@field name_sh_reload string
---@field buf_armor number
---@field text_lost string
---@field name_lo_temp string
---@field log_overheat number
---@field my_reactor_id number
---@field log_ammo_fire number
---@field my_paint number
---@field defence_energy_shield number
---@field have_torpedoes boolean
---@field mass_wep_type_draw table
---@field turbine_buf number
---@field special_debuf_coolent number
---@field c_b number
---@field stat_repair_drone number
---@field mimic_ammo_ratio_yellow number
---@field stat_energy_output number
---@field stat_dmg_red number
---@field paint_tex nil
---@field text_survived string
---@field log_damage_fire number
---@field resist_heat number
---@field bb_active_armor number
---@field original_speed number
---@field mech_battle_sprite_dead number
---@field deleted boolean
---@field mass_gun_id table
---@field buf_wire_plus number
---@field mirror number
---@field name_sh_hp string
---@field buf_ams number
---@field name_lo_speed string
---@field s_text_typing number
---@field bb_speed_damage number
---@field stat_cabin_safety number
---@field log_ammo_ballistic number
---@field load_ini boolean
---@field my_big_sprite number
---@field start_y number
---@field defence_destruct_sys number
---@field processor_program table
---@field num_of_modules number
---@field special_debuf_attack number
---@field stat_reload_time number
---@field armor_lr table
---@field new_item number
---@field stat_max_weight number
---@field electric_circuits_maximum number
---@field stat_energy_input number
---@field mimic_ammo_ratio_white number
---@field paint_me boolean
---@field mech_speed_buf number
---@field stat_dmg_blue number
---@field log_damage_ballistic number
---@field resist_current number
---@field original_resist_impact number
---@field mech_battle_sprite number
---@field can_have_melee number
---@field text_damaged string
---@field number_of_holders number
---@field aux_laser_heat number
---@field cur_item_type number
---@field buf_wire_minus number
---@field buf_paint number
---@field name_sh_armor string
---@field alpha_control number
---@field name_lo_reload string
---@field log_evasion number
---@field overclock number
---@field bb_reload_damage number
---@field stat_bonus_stability number
---@field my_num number
---@field mech_data_id table
---@field start_x number
---@field defence_active_armor number
---@field stat_speed number
---@field special_debuf_armor number
---@field custom_sprite string
---@field armor_layers number
---@field last_my number
---@field stat_max_temp number
---@field animation_save_sprite boolean
---@field mimic_ammo_ratio_red number
---@field name string
---@field stat_damage number
---@field my_pilot number
---@field original_resist_heat number
---@field number_of_guns number
---@field tired number
---@field name_lo_hp string
---@field bb_injure number
---@field stat_battle_time number
---@field my_metallite_price number
---@field circuits_using number
---@field mech_data number
---@field original_battle_time number
---@field change_name boolean
---@field have_reactor boolean
---@field last_mx number
---@field name_sh_weight string
---@field stat_dps number
---@field log_avg_dist number
---@field original_resist_current number
---@field my_eraser number
---@field sh_paint_sampler number
---@field defence_passive_armor number
---@field dead_pilot boolean
---@field change boolean
---@field c_r number
---@field new_module boolean
---@field cur_item number
---@field name_lo_armor string
---@field mech_number number
---@field bb_energy_shield number
---@field mech_change_id table
---@field shield_buff number
---@field original_armor number
---@field have_needles boolean
---@field name_sh_temp string
---@field stat_dmg_yellow number
---@field oxygen_multiplier number
---@field original_weight number
---@field log_ammo_rocket number
---@field battle_slot number
---@field original_reload_time number
---@field stat_armor number
---@field defence_mod_weight number
---@field heat_sink_module number
---@field have_cabin boolean
---@field number_of_deleted number
---@field special_debuf_speed number
---@field armor_lr_weight number
---@field cur_guns number
---@field item_pos number
---@field log_damage_rocket number
---@field bb_cool_damage number
---@field mech_battle_sprite_ver_attack number
---@field hit_points number
---@field created boolean
---@field name_sh_speed string
---@field name_lo_weight string
---@field stat_dmg_white number
---@field log_ammo_laser number
---@field my_paint_buf number
---@field hover boolean

---This is an auto generated class definition. 
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_big_holder_reactor
---@field press number
---@field have_bonus boolean
---@field mod_output number
---@field stat_energy number
---@field name string
---@field original_max_heat number
---@field plasma_coord_y number
---@field stat_weight number
---@field reactor_spr_big_stop number
---@field my_holder number
---@field i number
---@field name_stability string
---@field text_engine_off string
---@field load_ini boolean
---@field blink_ignite number
---@field start_y number
---@field original_coolent_power number
---@field buf_coolent_power number
---@field buf_sys_mult number
---@field plasma_coord_mult number
---@field reactor_spr_big number
---@field stat_coolent_power number
---@field original_weight number
---@field number_of_kernel number
---@field reactor_type number
---@field overcharge_output number
---@field buf_max_temp number
---@field name_output string
---@field mech_data number
---@field buf_work_heat number
---@field number_of_deleted number
---@field plasma_coord_z number
---@field surf_eng_off number
---@field max_press number
---@field reactor_spr_big_work number
---@field stat_work_heat number
---@field reaction number
---@field slowdown number
---@field additional_wires number
---@field buf_sys_external number
---@field reactor_reload_mod number
---@field name_weight string
---@field text_engine_running string
---@field buf_mod_output number
---@field name_limit string
---@field number_of_holders number
---@field item_pos number
---@field stat_max_heat number
---@field have_base boolean
---@field view_sprite number
---@field my_mech number
---@field stat_output number
---@field plasma_coord_x number
---@field reactor_spr_big_start number
---@field stat_system_buf number
---@field original_work_heat number
---@field reactor_number number
---@field my_num number
---@field mech_data_id table
---@field original_output number
---@field plasma_distance number
---@field created boolean
---@field start_x number
---@field reaction_multiplier number
---@field mod_max_temp number
---@field ignite number
---@field new_module boolean
---@field slowdown_multiplier number
---@field deleted boolean
---@field buf_sys_inner number
---@field reactor_spr number
---@field hover boolean

---This is an auto generated class definition. 
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_big_holder_weapon
---@field original_energy number
---@field set_point_weight number
---@field special_acc_buf number
---@field wep_prior table
---@field stat_energy number
---@field weapon_number number
---@field name string
---@field stat_penetration number
---@field buf_wire_plus number
---@field sound_pack number
---@field stat_weight number
---@field set_point_current number
---@field stat_damage number
---@field energy_buffed number
---@field rate_of_fire number
---@field weapon_type_num number
---@field my_holder number
---@field special_rtf_buf number
---@field change_x number
---@field special_buf_type number
---@field weapon_spr_big number
---@field original_penetration number
---@field start_y number
---@field special_ele_buf number
---@field set_point_max number
---@field special_weight_buf number
---@field original_accuracy number
---@field original_weight number
---@field special_num_buf number
---@field number_of_deleted number
---@field homing_power number
---@field size_huge number
---@field set_point_energy number
---@field check_special boolean
---@field special_sp_buf number
---@field change_y number
---@field original_rate_of_fire number
---@field number_of_holders number
---@field original_damage number
---@field item_pos number
---@field set_point_penetration number
---@field special_life_buf number
---@field my_mech number
---@field stat_dps number
---@field buf_wire_minus number
---@field set_point_accuracy number
---@field weapon_type string
---@field special_pen_buf number
---@field pretend_gun number
---@field special_buf_slow number
---@field my_num number
---@field weapon_spr number
---@field created boolean
---@field start_x number
---@field special_dmg_buf number
---@field set_point_fire_speed number
---@field original_speed number
---@field new_module boolean
---@field weapon_data number
---@field deleted boolean
---@field accuracy_fault number
---@field hover boolean
---@field blue_length number the range of a blue weapon

---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_content_magnet
---@field size_x number
---@field position_y number
---@field sort_anim number
---@field sort_now boolean
---@field list_magnet table
---@field array_lua table
---@field check_list boolean
---@field activated boolean
---@field position_x number
---@field size_y number
---@field sort_items number
---@field surf_magnet_normal number
---@field my_window number
---@field move_y number
---@field st_lua table
---@field scroll number
---@field number_of_deleted number
---@field item_height number
---@field number_of_items number

---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_content_mechs
---@field size_x number
---@field position_y number
---@field sort_anim number
---@field sort_now boolean
---@field surf_mech_normal number
---@field array_lua table
---@field activated boolean
---@field position_x number
---@field size_y number
---@field sort_items number
---@field my_window number
---@field move_y number
---@field st_lua table
---@field list_mech table
---@field scroll number
---@field number_of_deleted number
---@field item_height number
---@field number_of_items number

---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_content_weapons
---@field size_x number
---@field position_y number
---@field sort_anim number
---@field sort_now boolean
---@field array_lua table
---@field check_list boolean
---@field activated boolean
---@field position_x number
---@field size_y number
---@field sort_items number
---@field my_window number
---@field move_y number
---@field list_weapon table
---@field surf_weapon_normal number
---@field st_lua table
---@field scroll number
---@field number_of_deleted number
---@field item_height number
---@field number_of_items number

---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_content_solenoid
---@field size_x number
---@field position_y number
---@field sort_anim number
---@field list_solenoid table
---@field surf_solenoid_normal number
---@field sort_now boolean
---@field array_lua table
---@field check_list boolean
---@field activated boolean
---@field position_x number
---@field size_y number
---@field sort_items number
---@field my_window number
---@field move_y number
---@field st_lua table
---@field scroll number
---@field number_of_deleted number
---@field item_height number
---@field number_of_items number

---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_content_reactor
---@field size_x number
---@field position_y number
---@field sort_anim number
---@field sort_now boolean
---@field array_lua table
---@field check_list boolean
---@field activated boolean
---@field surf_reactor_normal number
---@field list_reactor table
---@field position_x number
---@field size_y number
---@field sort_items number
---@field my_window number
---@field move_y number
---@field st_lua table
---@field scroll number
---@field number_of_deleted number
---@field item_height number
---@field number_of_items number

--------------------------------------------
--Documentation for used mod functions -----
--------------------------------------------
--Added this file to give the IDE info on what the mod functions return and use for params
--Game is made in GameMaker
--See the gamemaker documentation for the implimentation of the global functions
--example: variable_global_set, ds_map_add, sprite_add
--the exposed functions can be found in the list_of_functions.txt file

---@type table<string, string>
mod_info = mod_info
---This function is used to create a new, empty DS map and will return a Handle to it which is then used to access the data structure in all other DS map functions.
---@type fun(): ds_map
ds_map_create = ds_map_create
---This function should be used to add sets of key/value pairs into the specified DS map.
---@type fun(map: ds_map, key: string, value: any)
ds_map_add = ds_map_add
---With this function you can retrieve all of the keys that a DS map contains.
---@type fun(id: ds_map) : table
ds_map_keys_to_array = ds_map_keys_to_array
---With this function you can get the value from a specified key.
---@type fun(id: ds_map, key: string) : any|nil
ds_map_find_value = ds_map_find_value
---This function returns an array with the variable names from a struct.
---@type fun(id: number) : table
struct_get_names = struct_get_names
---With this function you can set the value of a given global variable.
---@type fun(key: string, value: any)
variable_global_set = variable_global_set
---With this function you can get the value from a given named global variable
---@type fun(key: string): value: any
variable_global_get = variable_global_get
---This function will add an image as a sprite
---@type fun(filepath: string, number_of_images: number, removeback: boolean, smooth: boolean, xorig: number, yorig: number): value: number
sprite_add = sprite_add
---This function will merge the sprite indexed in argument 1 ("ind2") with that which is indexed in argument 0 ("ind1").
---@type fun(ind1: number, ind2: number)
sprite_merge = sprite_merge
---This function will return the index of a newly created sprite that is a duplicate (copy) of the one input as the "index" argument.
---@type fun(index: number) :number|-1
sprite_duplicate = sprite_duplicate
---This function will delete a sprite from the game, freeing any memory that was reserved for it.
---@type fun(index: number)
sprite_delete = sprite_delete
---This function gets the unique identifying index for a game asset from its name.
---@type fun(name: string): any
asset_get_index = asset_get_index
---This function creates a pop-up message box which displays the given string and a button marked "Ok" to close it.
---@type fun(message: string|number)
show_message = show_message
---With this function you can create a new instance of the specified object at any given point within the room and at the depth specified.
---@type fun(x: number, y: number, depth: number, obj: any): any
instance_create_depth = instance_create_depth
---With this function you can check if a key is pressed, as imput it uses virtual key codes
---@type fun(virtualKey: number)
keyboard_check_pressed = keyboard_check_pressed
---This function is used to create a surface and will return the index of the surface which should be stored in a variable for future function calls.
---@type fun(width: number, height: number)
surface_create = surface_create
---With this function you set all further drawing to the target surface rather than the screen and in this way you can tell GameMaker to only draw specific things to the specified surface.
---@type fun(surface_id: number)
surface_set_target = surface_set_target
---This function can be used to clear the entire screen with a given colour and the alpha component of the destination is set to the value you have set.
---@type fun(col_id: number, alpha: number)
draw_clear_alpha = draw_clear_alpha
---This function draws the given sprite and sub-image at a position.
---@type fun(sprite: number, subimg: number, x: number, y: number)
draw_sprite = draw_sprite
---This function resets all further drawing from the target surface back to the screen.
---@type fun()
surface_reset_target = surface_reset_target
---This function will save a surface to disc using the given filename. The surface must be saved as a *.png format file.
---@type fun(surface_id: number, fname: string)
surface_save = surface_save
---When you are working with surfaces, you should always use this function whenever you are finished using them.
---@type fun(surface_id: number)
surface_free = surface_free
---When you are working with surfaces, you should always use this function whenever you are finished using them.
---@type fun(ind:number, fname:string, imgnumb:number, removeback:boolean, smooth:boolean, xorig:number, yorig:number)
sprite_replace = sprite_replace