---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_component_shop_current_item
---@field change_x number
---@field change_y number
---@field comp_data_type number
---@field comp_type number
---@field item_pos number
---@field logo number
---@field logo_index number
---@field researched boolean
---@field size number
---@field size_x number
---@field size_y number