---@class ds_map A reference handle to the gamemaker ds_map data structure, stores key and value pairs.

---This is an auto generated class definition. 
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_research
---@field condition number 0|1|2|3 condition (0-closed, 1-opened, 2-researching, 3-researched)
---@field progression number
---@field res_type number
---@field opened number
---@field ln_res table
---@field give_item boolean when true indicates the research will give a free item upon completion
---@field researching_anim number
---@field text string
---@field res_number number the number for the research as found in the debug (F6) of the research screen (upper left white number)
---@field n_ln_res number
---@field require_staff number the number of required staff to research
---@field check_research number
---@field link table
---@field meet boolean
---@field array_lua table
---@field new_research boolean
---@field just_researched boolean
---@field blink number
---@field require_days_max number the initial required days to complete the research
---@field next_day number
---@field st_lua table
---@field res_under_type number
---@field require_days number the remaining days to complete the research
---@field text_days string
---@field text_staff string

---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_component_shop
---@field activated boolean
---@field add boolean
---@field array_lua table
---@field cabin_start_x number
---@field cabin_start_y number
---@field change boolean
---@field comp_beacon game_obj_component --the shop component for the beacon
---@field comp_cabin game_obj_component[] --array containing the shop components for cabins
---@field comp_city_parts game_obj_component --the shop component for the city parts
---@field comp_engineer game_obj_component --the shop component for the engineer
---@field comp_injector game_obj_component[] --array containing the shop components for injectors
---@field comp_kernel game_obj_component[] --array containing the shop components for kernels
---@field comp_lr_armor_end game_obj_component[] --array containing the shop components for end armor
---@field comp_lr_armor_middle game_obj_component[] --array containing the shop components for middle armor
---@field comp_magnet game_obj_component[] --array containing the shop components for magnets
---@field comp_mech game_obj_component[] --array containing the shop components for mechs
---@field comp_motor game_obj_component[] --array containing the shop components for motos
---@field comp_piston game_obj_component[] --array containing the shop components for pistons
---@field comp_reactor game_obj_component[] --array containing the shop components for reactors
---@field comp_rocket game_obj_component --the shop component for the rocket
---@field comp_safety game_obj_component[] --array containing the shop components for safety
---@field comp_solenoid game_obj_component[] --array containing the shop components for solenoids
---@field comp_wep game_obj_component[] --array containing the shop components for weapons
---@field cur_item number
---@field cur_item_type number
---@field days_left number
---@field disassemble_pressed number
---@field hangar_order number
---@field hanger_mass table
---@field injector_start_x number
---@field injector_start_y number
---@field kernel_start_x number
---@field kernel_start_y number
---@field light_up_table boolean
---@field mech_start_x number
---@field mech_start_y number
---@field minus_place number
---@field motor_start_x number
---@field motor_start_y number
---@field new_item_data_type number
---@field new_item_type number
---@field next_day boolean
---@field order_pressed number
---@field piston_start_x number
---@field piston_start_y number
---@field play_sound boolean
---@field price_bjorn number
---@field price_metallite number
---@field price_munilon number
---@field price_skalaknit number
---@field price_staff number
---@field reactor_start_x number
---@field reactor_start_y number
---@field research_weapon_size boolean
---@field safety_start_x number
---@field safety_start_y number
---@field show_menu boolean
---@field show_menu_img number
---@field st_lua table
---@field t_armor_parts number
---@field t_city_parts number
---@field t_reaction_slowdown number
---@field text_accuracy string
---@field text_armor string
---@field text_armor_parts string
---@field text_aux string
---@field text_battle string
---@field text_beacon string
---@field text_bjorn string
---@field text_city_parts string
---@field text_control string
---@field text_coolent string
---@field text_current_res string
---@field text_damage string
---@field text_days string
---@field text_district string
---@field text_energy string
---@field text_firespeed string
---@field text_heat string
---@field text_heat_res string
---@field text_impact_res string
---@field text_induction string
---@field text_max_pressure string
---@field text_menu_add string
---@field text_menu_hangar_a string
---@field text_menu_hangar_b string
---@field text_menu_mechs string
---@field text_menu_order string
---@field text_menu_reactors string
---@field text_menu_support string
---@field text_menu_to_disassemble string
---@field text_menu_to_order string
---@field text_menu_weapon_size string
---@field text_menu_weapons string
---@field text_metallite string
---@field text_move_x string
---@field text_move_y string
---@field text_move_z string
---@field text_multiplier string
---@field text_munilon string
---@field text_output string
---@field text_penetration string
---@field text_power_motor string
---@field text_power_solenoid string
---@field text_pressure string
---@field text_reaction string
---@field text_reload string
---@field text_rocket string
---@field text_safety string
---@field text_skalaknit string
---@field text_slowdown string
---@field text_speed_mech string
---@field text_speed_motor string
---@field text_staff string
---@field text_temp string
---@field text_weapons string
---@field text_weight string
---@field weapon_size number
---@field weapon_start_x number
---@field weapon_start_y number
---@field wheel_size_img number

---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_component
---@field comp_data_type number the index number of the component
---@field comp_type ComponentType the type of component
---@field item_pos number
---@field logo number the index of the sprite, use -4 to auto set it
---@field logo_index number
---@field researched boolean when true the component can be constructed
---@field size ComponentSize the size of the component when constructing it.
---@field size_x number
---@field size_y number

---This is an auto generated class definition. 
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_battle_map
---@field enemy_next number
---@field light_num number
---@field camera_center_y number
---@field monster_count number
---@field number_of_alife_mechs number
---@field map_mask number
---@field time_to_spawn boolean
---@field manual_order_time number
---@field sound_tank_high_freq number
---@field point_B_y number
---@field fullscreen_battle boolean
---@field mission_time_rising number
---@field main_data_sound table
---@field sound_laser_med_freq number
---@field buf_mnstr_sp number
---@field sound_corrosion_low_freq number
---@field boss_maze table
---@field fast_room boolean
---@field palettes_tex nil
---@field wave_reload_time_climax number
---@field battle_full_time number
---@field surf_circle_effects number
---@field text_entering string
---@field text_artillery string
---@field text_actions string
---@field mon_con_base number
---@field giant_new_phase boolean
---@field text_no_artillery string
---@field map_storm boolean
---@field sound_plasma_high_freq number
---@field main_sounds_amount number
---@field sound_fastrocket_low_freq number
---@field maay number
---@field continue_left number
---@field first_battle number
---@field minimap_row number
---@field lut_number number
---@field save_gif boolean
---@field was_defending_city boolean
---@field collect_sound number
---@field swarm_next number
---@field even table
---@field text_legend_bosses string
---@field load_leg_damage table
---@field camera_center_x number
---@field next_second boolean
---@field map_logic_task number
---@field leader_id number
---@field point_B_x number
---@field text_wrong_position string
---@field mission_time_resolution number
---@field sound_laser_low_freq number
---@field buf_metallite_reward number
---@field text_mech_not_selected string
---@field sound_corrosion_high_freq number
---@field l_y number
---@field boss_id number
---@field wave_max_rising number
---@field show_no_artillery_message number
---@field surf_slowdown_tex number
---@field text_scanning string
---@field red_maze table
---@field battle_copy_surf number
---@field underwater_part_type number
---@field surf_circle_artillery number
---@field have_enemy_base boolean
---@field storm_part_type number
---@field gold_maze table
---@field map_type number
---@field giant_id number
---@field text_new_position string
---@field map_cell_danger number
---@field last_maze_manual_order number
---@field sound_fastrocket_high_freq number
---@field pilot_talk_order number
---@field maax number
---@field wave_time_rising number
---@field text_targets string
---@field text_slow string
---@field surf_global_lum number
---@field text_retreat_progress string
---@field text_failed string
---@field reactivate_spawns boolean
---@field srf_minimap number
---@field camera number
---@field gif_image number
---@field text_order_special string
---@field sound_railgun_med_freq number
---@field point_A_y number
---@field mission_time_climax number
---@field sound_laser_high_freq number
---@field text_mech_dead string
---@field wheel_action number
---@field l_x number
---@field boss_dead boolean
---@field bjorn_reward number
---@field wave_max_resolution number
---@field text_legend_walls string
---@field battle_surf number
---@field surf_map_art number
---@field underwater_part number
---@field munillon_reward number
---@field light_sys_mass table
---@field storm_part number
---@field gold_buf table
---@field giant_damage_y number
---@field map_biohazard boolean
---@field sound_minigun_med_freq number
---@field wipe_enemy_base boolean
---@field mini_progress number
---@field skalaknit_reward number
---@field wave_time_resolution number
---@field show_wrong_pos_message number
---@field text_speedup string
---@field battle_pause boolean
---@field load_damaged_giant boolean
---@field surf_gen_map number
---@field start_close_anim boolean
---@field old_mech_phy_id table
---@field text_available string
---@field cam_y number
---@field grid_low number
---@field text_progress string
---@field giant_type number
---@field text_order_retreat string
---@field point_A_x number
---@field sound_railgun_low_freq number
---@field manual_order number
---@field new_grid number
---@field buf_skalaknit_reward number
---@field mission_stage string
---@field sound_flame_med_freq number
---@field buf_eng_reward number
---@field first_pause number
---@field an_time number
---@field boss_count number
---@field wave_max_climax number
---@field mech_slot_target table
---@field text_legend_squad string
---@field battle_speed_timer number
---@field mech_id table
---@field text_focus_fire string
---@field one_of_mech_swallowed boolean
---@field start boolean
---@field storm_move_timer number
---@field camera_zoom number
---@field giant_damage_x number
---@field map_resource number
---@field spawner_mass table
---@field sound_tesla_many number
---@field map_amount_turrets number
---@field sound_minigun_low_freq number
---@field buf_munillon_reward number
---@field winning_present_count number
---@field text_tutorial_B string
---@field blue_maze table
---@field wave_time_climax number
---@field add_stage_progress boolean
---@field retreat_mission boolean
---@field mech_phy_id table
---@field enter_enemy_base boolean
---@field cam_x number
---@field giant_ph_scream boolean
---@field text_order_fire string
---@field manual_camera boolean
---@field sound_railgun_high_freq number
---@field buf_sci_reward number
---@field mission_progress number
---@field sound_flame_low_freq number
---@field action_move_time number
---@field mech_selecting_y number
---@field text_legend_resources string
---@field show_labyrinth_legend boolean
---@field stage_progress number
---@field enemy_sys_mass table
---@field monster_pull_type number
---@field light_next number
---@field map_number number
---@field sound_tank_med_freq number
---@field map_amount_spawners number
---@field thing_created boolean
---@field mnstr_sp number
---@field sound_minigun_high_freq number
---@field buf_monster_count number
---@field boss_time_to_move number
---@field add_resource number
---@field wave_reload_time_rising number
---@field text_inside string
---@field battle_mechs_page number
---@field text_giant_near string
---@field move_line_num number
---@field progressing boolean
---@field scan_for_enemy_base number
---@field mon_con_empty number
---@field giant_ph_rest boolean
---@field text_order_basic string
---@field artillery_shells number
---@field make_it_dark number
---@field sound_plasma_med_freq number
---@field sound_flame_high_freq number
---@field count_gif number
---@field metallite_reward number
---@field weapon_data_sound table
---@field text_temp string
---@field action_last_sound number
---@field rob table
---@field swarm_sys_mass table
---@field mech_selecting_x number
---@field text_legend_exits string
---@field show_giant_is_near number
---@field v_grid number
---@field text_complete string
---@field sh_color_LUT_sampler number
---@field base_plant number
---@field enemy_num number
---@field st_lua table
---@field camera_radius number
---@field monster_max number
---@field scroll number
---@field map_music_task number
---@field map_amount_brucus number
---@field sound_tank_low_freq number
---@field sound_minigun_far number
---@field sound_corrosion_med_freq number
---@field sand_storm boolean
---@field text_tutorial_A string
---@field wave_reload_time_resolution number
---@field surf_mega_light number
---@field battle_gif_surf number
---@field text_entering_long string
---@field ending_task boolean
---@field mon_con_defence number
---@field giant_ph_chase boolean
---@field text_no_base string
---@field map_task number
---@field array_lua table
---@field sound_plasma_low_freq number
---@field tab_time number
---@field sound_fastrocket_med_freq number
---@field buf_bjorn_reward number
---@field minimap_show_big boolean
---@field swarm_num number
---@field mech_selecting boolean
---@field text_legend_enemies string
---@field show_found_base_message number

---This is an auto generated class definition. 
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_weapon_test
---@field text_accuracy string
---@field move_x number
---@field overall_damage_mass table
---@field hit_nmbr number
---@field text_shots string
---@field current_type number
---@field show_energy_sim number
---@field test_reload_time_red number
---@field overall_damage number
---@field damage_nmbr number
---@field hit_mass table
---@field weapon_description table
---@field start number
---@field text_dest_armor string
---@field single_mod number
---@field load_ini boolean
---@field test_copy_surf number
---@field text_damage string
---@field armor_buf number
---@field miss_nmbr number
---@field target number
---@field test_surf number
---@field damage_mass table
---@field water_mod number
---@field simulate_energy number
---@field gun_id number
---@field activated boolean
---@field miss_mass table
---@field text_hits string
---@field test_reload_time_yellow number
---@field monitor_img number
---@field simulate_aux number
---@field scroll number
---@field test_reload_time_white number
---@field text_misses string
---@field text_pot_damage string

---This is an auto generated class definition. 
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_research_panel
---@field double_click boolean
---@field tree_slot_height number
---@field min_size_x number
---@field research_surf number
---@field last_y number
---@field size_ratio number
---@field number_of_res number
---@field old_ms_y number
---@field mres table[] contains the research items that will be put on the research tree, does not contain the reference to the current research state see game_research_item for that
---@field tree_number number
---@field last_x number
---@field old_ms_x number
---@field tree_width number
---@field last_m_x number
---@field research_desc_move number
---@field base_size_h number
---@field array_lua table
---@field max_size_x number
---@field activated boolean
---@field size_y number
---@field tree_slot_width number
---@field st_lua table
---@field sp_zoom number
---@field size_x number

---This is an auto generated class definition. 
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_big_holder
---@field text_menu_reload string
---@field text_menu_weight string
---@field discket_ammo_ratio_yellow number
---@field walk_holder table
---@field armor_lr_have_copy table
---@field new_item_type number
---@field text_menu_test string
---@field text_blueprint_empty string
---@field camera_zoom number
---@field discket_melee number
---@field test_surf number
---@field ignite_open boolean
---@field discket_ammo_ratio_red number
---@field text_menu_energy string
---@field cur_sprite_stop number
---@field mech_extra_layer number
---@field save_blueprint_animation number
---@field armor_lr table
---@field monitor_img number
---@field new_item number
---@field reactor_type number
---@field text_menu_send string
---@field st_lua table
---@field scroll number
---@field discket_destruct number
---@field text_menu_ignite string
---@field send_open boolean
---@field text_blueprint_have string
---@field cur_sprite number
---@field text_battle_cost string
---@field cur_item_type number
---@field processor_program_researched boolean
---@field discket_ammo_ratio_white number
---@field test_copy_surf number
---@field cur_sprite_work number
---@field armor_lr_have table
---@field reactor_type_anim number
---@field change boolean
---@field array_lua table
---@field activated boolean
---@field discket_energy_shield number
---@field clean boolean
---@field cur_item number
---@field discket_active_armor number
---@field text_blueprint_type string
---@field change_item_time number
---@field cur_sprite_start number
---@field armor_layers number

---This is an auto generated class definition. 
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_big_holder_mech
---@field defence_melee number
---@field dead boolean
---@field stat_weight number
---@field special_debuf_health number
---@field c_g number
---@field new_item_type number
---@field stat_evasion number
---@field size_paint number
---@field log_damage_laser number
---@field output_for_small_holder number
---@field resist_impact number
---@field bb_armor_damage number
---@field mech_name string
---@field mech_battle_sprite_hor_attack number
---@field have_gun boolean
---@field more_info boolean
---@field name_sh_reload string
---@field buf_armor number
---@field text_lost string
---@field name_lo_temp string
---@field log_overheat number
---@field my_reactor_id number
---@field log_ammo_fire number
---@field my_paint number
---@field defence_energy_shield number
---@field have_torpedoes boolean
---@field mass_wep_type_draw table
---@field turbine_buf number
---@field special_debuf_coolent number
---@field c_b number
---@field stat_repair_drone number
---@field mimic_ammo_ratio_yellow number
---@field stat_energy_output number
---@field stat_dmg_red number
---@field paint_tex nil
---@field text_survived string
---@field log_damage_fire number
---@field resist_heat number
---@field bb_active_armor number
---@field original_speed number
---@field mech_battle_sprite_dead number
---@field deleted boolean
---@field mass_gun_id table
---@field buf_wire_plus number
---@field mirror number
---@field name_sh_hp string
---@field buf_ams number
---@field name_lo_speed string
---@field s_text_typing number
---@field bb_speed_damage number
---@field stat_cabin_safety number
---@field log_ammo_ballistic number
---@field load_ini boolean
---@field my_big_sprite number
---@field start_y number
---@field defence_destruct_sys number
---@field processor_program table
---@field num_of_modules number
---@field special_debuf_attack number
---@field stat_reload_time number
---@field armor_lr table
---@field new_item number
---@field stat_max_weight number
---@field electric_circuits_maximum number
---@field stat_energy_input number
---@field mimic_ammo_ratio_white number
---@field paint_me boolean
---@field mech_speed_buf number
---@field stat_dmg_blue number
---@field log_damage_ballistic number
---@field resist_current number
---@field original_resist_impact number
---@field mech_battle_sprite number
---@field can_have_melee number
---@field text_damaged string
---@field number_of_holders number
---@field aux_laser_heat number
---@field cur_item_type number
---@field buf_wire_minus number
---@field buf_paint number
---@field name_sh_armor string
---@field alpha_control number
---@field name_lo_reload string
---@field log_evasion number
---@field overclock number
---@field bb_reload_damage number
---@field stat_bonus_stability number
---@field my_num number
---@field mech_data_id table
---@field start_x number
---@field defence_active_armor number
---@field stat_speed number
---@field special_debuf_armor number
---@field custom_sprite string
---@field armor_layers number
---@field last_my number
---@field stat_max_temp number
---@field animation_save_sprite boolean
---@field mimic_ammo_ratio_red number
---@field name string
---@field stat_damage number
---@field my_pilot number
---@field original_resist_heat number
---@field number_of_guns number
---@field tired number
---@field name_lo_hp string
---@field bb_injure number
---@field stat_battle_time number
---@field my_metallite_price number
---@field circuits_using number
---@field mech_data number
---@field original_battle_time number
---@field change_name boolean
---@field have_reactor boolean
---@field last_mx number
---@field name_sh_weight string
---@field stat_dps number
---@field log_avg_dist number
---@field original_resist_current number
---@field my_eraser number
---@field sh_paint_sampler number
---@field defence_passive_armor number
---@field dead_pilot boolean
---@field change boolean
---@field c_r number
---@field new_module boolean
---@field cur_item number
---@field name_lo_armor string
---@field mech_number number
---@field bb_energy_shield number
---@field mech_change_id table
---@field shield_buff number
---@field original_armor number
---@field have_needles boolean
---@field name_sh_temp string
---@field stat_dmg_yellow number
---@field oxygen_multiplier number
---@field original_weight number
---@field log_ammo_rocket number
---@field battle_slot number
---@field original_reload_time number
---@field stat_armor number
---@field defence_mod_weight number
---@field heat_sink_module number
---@field have_cabin boolean
---@field number_of_deleted number
---@field special_debuf_speed number
---@field armor_lr_weight number
---@field cur_guns number
---@field item_pos number
---@field log_damage_rocket number
---@field bb_cool_damage number
---@field mech_battle_sprite_ver_attack number
---@field hit_points number
---@field created boolean
---@field name_sh_speed string
---@field name_lo_weight string
---@field stat_dmg_white number
---@field log_ammo_laser number
---@field my_paint_buf number
---@field hover boolean

---This is an auto generated class definition. 
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_big_holder_reactor
---@field press number
---@field have_bonus boolean
---@field mod_output number
---@field stat_energy number
---@field name string
---@field original_max_heat number
---@field plasma_coord_y number
---@field stat_weight number
---@field reactor_spr_big_stop number
---@field my_holder number
---@field i number
---@field name_stability string
---@field text_engine_off string
---@field load_ini boolean
---@field blink_ignite number
---@field start_y number
---@field original_coolent_power number
---@field buf_coolent_power number
---@field buf_sys_mult number
---@field plasma_coord_mult number
---@field reactor_spr_big number
---@field stat_coolent_power number
---@field original_weight number
---@field number_of_kernel number
---@field reactor_type number
---@field overcharge_output number
---@field buf_max_temp number
---@field name_output string
---@field mech_data number
---@field buf_work_heat number
---@field number_of_deleted number
---@field plasma_coord_z number
---@field surf_eng_off number
---@field max_press number
---@field reactor_spr_big_work number
---@field stat_work_heat number
---@field reaction number
---@field slowdown number
---@field additional_wires number
---@field buf_sys_external number
---@field reactor_reload_mod number
---@field name_weight string
---@field text_engine_running string
---@field buf_mod_output number
---@field name_limit string
---@field number_of_holders number
---@field item_pos number
---@field stat_max_heat number
---@field have_base boolean
---@field view_sprite number
---@field my_mech number
---@field stat_output number
---@field plasma_coord_x number
---@field reactor_spr_big_start number
---@field stat_system_buf number
---@field original_work_heat number
---@field reactor_number number
---@field my_num number
---@field mech_data_id table
---@field original_output number
---@field plasma_distance number
---@field created boolean
---@field start_x number
---@field reaction_multiplier number
---@field mod_max_temp number
---@field ignite number
---@field new_module boolean
---@field slowdown_multiplier number
---@field deleted boolean
---@field buf_sys_inner number
---@field reactor_spr number
---@field hover boolean

---This is an auto generated class definition. 
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_big_holder_weapon
---@field original_energy number
---@field set_point_weight number
---@field special_acc_buf number
---@field wep_prior table
---@field stat_energy number
---@field weapon_number number
---@field name string
---@field stat_penetration number
---@field buf_wire_plus number
---@field sound_pack number
---@field stat_weight number
---@field set_point_current number
---@field stat_damage number
---@field energy_buffed number
---@field rate_of_fire number
---@field weapon_type_num number
---@field my_holder number
---@field special_rtf_buf number
---@field change_x number
---@field special_buf_type number
---@field weapon_spr_big number
---@field original_penetration number
---@field start_y number
---@field special_ele_buf number
---@field set_point_max number
---@field special_weight_buf number
---@field original_accuracy number
---@field original_weight number
---@field special_num_buf number
---@field number_of_deleted number
---@field homing_power number
---@field size_huge number
---@field set_point_energy number
---@field check_special boolean
---@field special_sp_buf number
---@field change_y number
---@field original_rate_of_fire number
---@field number_of_holders number
---@field original_damage number
---@field item_pos number
---@field set_point_penetration number
---@field special_life_buf number
---@field my_mech number
---@field stat_dps number
---@field buf_wire_minus number
---@field set_point_accuracy number
---@field weapon_type string
---@field special_pen_buf number
---@field pretend_gun number
---@field special_buf_slow number
---@field my_num number
---@field weapon_spr number
---@field created boolean
---@field start_x number
---@field special_dmg_buf number
---@field set_point_fire_speed number
---@field original_speed number
---@field new_module boolean
---@field weapon_data number
---@field deleted boolean
---@field accuracy_fault number
---@field hover boolean
---@field blue_length number the range of a blue weapon

---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_content_magnet
---@field size_x number
---@field position_y number
---@field sort_anim number
---@field sort_now boolean
---@field list_magnet table
---@field array_lua table
---@field check_list boolean
---@field activated boolean
---@field position_x number
---@field size_y number
---@field sort_items number
---@field surf_magnet_normal number
---@field my_window number
---@field move_y number
---@field st_lua table
---@field scroll number
---@field number_of_deleted number
---@field item_height number
---@field number_of_items number

---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_content_mechs
---@field size_x number
---@field position_y number
---@field sort_anim number
---@field sort_now boolean
---@field surf_mech_normal number
---@field array_lua table
---@field activated boolean
---@field position_x number
---@field size_y number
---@field sort_items number
---@field my_window number
---@field move_y number
---@field st_lua table
---@field list_mech table
---@field scroll number
---@field number_of_deleted number
---@field item_height number
---@field number_of_items number

---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_content_weapons
---@field size_x number
---@field position_y number
---@field sort_anim number
---@field sort_now boolean
---@field array_lua table
---@field check_list boolean
---@field activated boolean
---@field position_x number
---@field size_y number
---@field sort_items number
---@field my_window number
---@field move_y number
---@field list_weapon table
---@field surf_weapon_normal number
---@field st_lua table
---@field scroll number
---@field number_of_deleted number
---@field item_height number
---@field number_of_items number

---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_content_solenoid
---@field size_x number
---@field position_y number
---@field sort_anim number
---@field list_solenoid table
---@field surf_solenoid_normal number
---@field sort_now boolean
---@field array_lua table
---@field check_list boolean
---@field activated boolean
---@field position_x number
---@field size_y number
---@field sort_items number
---@field my_window number
---@field move_y number
---@field st_lua table
---@field scroll number
---@field number_of_deleted number
---@field item_height number
---@field number_of_items number

---This is an auto generated class definition.
---
---Please use the found values as a starting point for your use.
---As not all values may be present at every point of the game.
---Or values could be missing from the definition.
---@class game_obj_content_reactor
---@field size_x number
---@field position_y number
---@field sort_anim number
---@field sort_now boolean
---@field array_lua table
---@field check_list boolean
---@field activated boolean
---@field surf_reactor_normal number
---@field list_reactor table
---@field position_x number
---@field size_y number
---@field sort_items number
---@field my_window number
---@field move_y number
---@field st_lua table
---@field scroll number
---@field number_of_deleted number
---@field item_height number
---@field number_of_items number

--------------------------------------------
--Documentation for used mod functions -----
--------------------------------------------
--Added this file to give the IDE info on what the mod functions return and use for params
--Game is made in GameMaker
--See the gamemaker documentation for the implimentation of the global functions
--example: variable_global_set, ds_map_add, sprite_add
--the exposed functions can be found in the list_of_functions.txt file

---@type table<string, string>
mod_info = mod_info
---This function is used to create a new, empty DS map and will return a Handle to it which is then used to access the data structure in all other DS map functions.
---@type fun(): ds_map
ds_map_create = ds_map_create
---This function should be used to add sets of key/value pairs into the specified DS map.
---@type fun(map: ds_map, key: string, value: any)
ds_map_add = ds_map_add
---With this function you can retrieve all of the keys that a DS map contains.
---@type fun(id: ds_map) : table
ds_map_keys_to_array = ds_map_keys_to_array
---With this function you can get the value from a specified key.
---@type fun(id: ds_map, key: string) : any|nil
ds_map_find_value = ds_map_find_value
---This function returns an array with the variable names from a struct.
---@type fun(id: number) : table
struct_get_names = struct_get_names
---With this function you can set the value of a given global variable.
---@type fun(key: string, value: any)
variable_global_set = variable_global_set
---With this function you can get the value from a given named global variable
---@type fun(key: string): value: any
variable_global_get = variable_global_get
---This function will add an image as a sprite
---@type fun(filepath: string, number_of_images: number, removeback: boolean, smooth: boolean, xorig: number, yorig: number): value: number
sprite_add = sprite_add
---This function will merge the sprite indexed in argument 1 ("ind2") with that which is indexed in argument 0 ("ind1").
---@type fun(ind1: number, ind2: number)
sprite_merge = sprite_merge
---This function will return the index of a newly created sprite that is a duplicate (copy) of the one input as the "index" argument.
---@type fun(index: number) :number|-1
sprite_duplicate = sprite_duplicate
---This function will delete a sprite from the game, freeing any memory that was reserved for it.
---@type fun(index: number)
sprite_delete = sprite_delete
---This function gets the unique identifying index for a game asset from its name.
---@type fun(name: string): any
asset_get_index = asset_get_index
---This function creates a pop-up message box which displays the given string and a button marked "Ok" to close it.
---@type fun(message: string|number)
show_message = show_message
---With this function you can create a new instance of the specified object at any given point within the room and at the depth specified.
---@type fun(x: number, y: number, depth: number, obj: any): any
instance_create_depth = instance_create_depth
---With this function you can check if a key is pressed, as imput it uses virtual key codes
---@type fun(virtualKey: number)
keyboard_check_pressed = keyboard_check_pressed
---This function is used to create a surface and will return the index of the surface which should be stored in a variable for future function calls.
---@type fun(width: number, height: number)
surface_create = surface_create
---With this function you set all further drawing to the target surface rather than the screen and in this way you can tell GameMaker to only draw specific things to the specified surface.
---@type fun(surface_id: number)
surface_set_target = surface_set_target
---This function can be used to clear the entire screen with a given colour and the alpha component of the destination is set to the value you have set.
---@type fun(col_id: number, alpha: number)
draw_clear_alpha = draw_clear_alpha
---This function draws the given sprite and sub-image at a position.
---@type fun(sprite: number, subimg: number, x: number, y: number)
draw_sprite = draw_sprite
---This function resets all further drawing from the target surface back to the screen.
---@type fun()
surface_reset_target = surface_reset_target
---This function will save a surface to disc using the given filename. The surface must be saved as a *.png format file.
---@type fun(surface_id: number, fname: string)
surface_save = surface_save
---When you are working with surfaces, you should always use this function whenever you are finished using them.
---@type fun(surface_id: number)
surface_free = surface_free
---When you are working with surfaces, you should always use this function whenever you are finished using them.
---@type fun(ind:number, fname:string, imgnumb:number, removeback:boolean, smooth:boolean, xorig:number, yorig:number)
sprite_replace = sprite_replace