--------------------------------------------
--Documentation for used mod functions -----
--------------------------------------------
--Added this file to give the IDE info on what the mod functions return and use for params

---@type any
mod_info = mod_info;
---This function is used to create a new, empty DS map and will return a Handle to it which is then used to access the data structure in all other DS map functions.
---@type fun(): ds_map
ds_map_create = ds_map_create;
---This function should be used to add sets of key/value pairs into the specified DS map.
---@type fun(map: ds_map, key: string, value: any)
ds_map_add = ds_map_add;
---With this function you can retrieve all of the keys that a DS map contains.
---@type fun(id: ds_map) : table
ds_map_keys_to_array = ds_map_keys_to_array;
---With this function you can get the value from a specified key.
---@type fun(id: ds_map, key: string) : any|nil
ds_map_find_value = ds_map_find_value;
---This function returns an array with the variable names from a struct.
---@type fun(id: number) : table
struct_get_names = struct_get_names;
---With this function you can set the value of a given global variable.
---@type fun(key: string, value: any)
variable_global_set = variable_global_set;
---With this function you can get the value from a given named global variable
---@type fun(key: string): value: any
variable_global_get = variable_global_get;
---This function will add an image as a sprite
---@type fun(filepath: string, number_of_images: number, removeback: boolean, smooth: boolean, xorig: number, yorig: number): value: number
sprite_add = sprite_add;
---This function will merge the sprite indexed in argument 1 ("ind2") with that which is indexed in argument 0 ("ind1").
---@type fun(ind1: number, ind2: number)
sprite_merge = sprite_merge;
---This function will return the index of a newly created sprite that is a duplicate (copy) of the one input as the "index" argument.
---@type fun(index: number) :number|-1
sprite_duplicate = sprite_duplicate;
---This function will delete a sprite from the game, freeing any memory that was reserved for it.
---@type fun(index: number)
sprite_delete = sprite_delete;
---This function gets the unique identifying index for a game asset from its name.
---@type fun(name: string): any
asset_get_index = asset_get_index;
---This function creates a pop-up message box which displays the given string and a button marked "Ok" to close it.
---@type fun(message: string)
show_message = show_message;
---With this function you can create a new instance of the specified object at any given point within the room and at the depth specified.
---@type fun(x: number, y: number, depth: number, obj: any): any
instance_create_depth = instance_create_depth;
---With this function you can check if a key is pressed, as imput it uses virtual key codes
---@type fun(virtualKey: number)
keyboard_check_pressed = keyboard_check_pressed;
--------------------------------------------
--------------------------------------------
-- Virtual Key Codes
-- 
-- // Control keys
-- Backspace = 8,
-- Tab = 9,
-- Enter = 13,
-- Shift = 16,
-- Ctrl = 17,
-- Alt = 18,
-- PauseBreak = 19,
-- CapsLock = 20,
-- Escape = 27,
-- Space = 32,
-- PageUp = 33,
-- PageDown = 34,
-- End = 35,
-- Home = 36,
-- ArrowLeft = 37,
-- ArrowUp = 38,
-- ArrowRight = 39,
-- ArrowDown = 40,
-- Insert = 45,
-- Delete = 46,
-- 
-- // Number row
-- D0 = 48,
-- D1 = 49,
-- D2 = 50,
-- D3 = 51,
-- D4 = 52,
-- D5 = 53,
-- D6 = 54,
-- D7 = 55,
-- D8 = 56,
-- D9 = 57,
-- 
-- // Letters
-- A = 65,
-- B = 66,
-- C = 67,
-- D = 68,
-- E = 69,
-- F = 70,
-- G = 71,
-- H = 72,
-- I = 73,
-- J = 74,
-- K = 75,
-- L = 76,
-- M = 77,
-- N = 78,
-- O = 79,
-- P = 80,
-- Q = 81,
-- R = 82,
-- S = 83,
-- T = 84,
-- U = 85,
-- V = 86,
-- W = 87,
-- X = 88,
-- Y = 89,
-- Z = 90,
-- 
-- // Windows / Meta
-- LeftWindows = 91,
-- RightWindows = 92,
-- Select = 93,
-- 
-- // Numpad
-- NumPad0 = 96,
-- NumPad1 = 97,
-- NumPad2 = 98,
-- NumPad3 = 99,
-- NumPad4 = 100,
-- NumPad5 = 101,
-- NumPad6 = 102,
-- NumPad7 = 103,
-- NumPad8 = 104,
-- NumPad9 = 105,
-- Multiply = 106,
-- Add = 107,
-- Subtract = 109,
-- Decimal = 110,
-- Divide = 111,
-- 
-- // Function keys
-- F1 = 112,
-- F2 = 113,
-- F3 = 114,
-- F4 = 115,
-- F5 = 116,
-- F6 = 117,
-- F7 = 118,
-- F8 = 119,
-- F9 = 120,
-- F10 = 121,
-- F11 = 122,
-- F12 = 123,
-- 
-- // Lock keys
-- NumLock = 144,
-- ScrollLock = 145,
-- 
-- // Punctuation
-- Semicolon = 186,
-- Equal = 187,
-- Comma = 188,
-- Minus = 189,
-- Period = 190,
-- Slash = 191,
-- Backquote = 192,
-- BracketLeft = 219,
-- Backslash = 220,
-- BracketRight = 221,
-- Quote = 222
--------------------------------------------
--------------------------------------------